version: '3.8'

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    deploy:
      placement:
        constraints:
          - 'node.labels.registry == true'
#    environment:
#      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
#      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
#      REGISTRY_AUTH: htpasswd
#      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
#      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - "/c/tmp/docker/registry:/var/lib/registry"
